name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libncursesw5-dev ccache

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Build
        run: make build

      - name: Test
        run: make test
